### ISSUE TITLE
Fail with noise

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#258]
In `academy2016` if we make the YAML illegal:

```
---
title: CoDe Academy
nav_weight: 10
weight: 10
brand-txt: >
    *Co*{: style='color: black; font-style: normal;'}De
    Aca*de*{: style="color: black; font-style: normal;"}my<!--power-icon-->
subtitle: >
  A modern continuous delivery bootcamp for graduates
caption: >
  Four Continuous Delivery Bootcamps - in Denmark and Norway. Each is 5 intense days. Bring your laptop! FREE to attend for Computer Science students and unemployed IT professionals. Enroll NOW!
color: '#f58532'
is_container: true
date_:      2016-06-13
date_end:   2016-09-02
city:       Throughout Scandinavia
event_header:
  img: ../images/pages/academy2016/event-main.jpg
    ribbon: Enroll today
checkout:
  eventbriteid: 24573031599
css_class: academy
sponsors:
  - github
  - napatech
  - danfoss
  - bkultrasound
---

```

The  sponsor include produces no output.

Make the includes fail with noise: Print error to the screen, ...and the console
