### ISSUE TITLE
Abstract should be available for all speakers

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#63]
Currently we're only showing the abstract of the speaks for the keynote speakers.

The abstract should also be available for ordinary speakers - hover? pop-up?

...Any ideas anyone?

@jonnycoull @meekrosoft @illus0r

**Comment by lakruzz** [comment]
A speakers page!!!

**Comment by lakruzz** [comment]
@jonnycoull @illus0r 

I need an idea and an estimate on how we can achieve this. Have a look at the [Code CPH](http://www.code-conf.com/code-cph-2016/)

The abstract of the speak i shown for the keynote speakers: 

![image](https://cloud.githubusercontent.com/assets/155492/14540105/b258db42-0283-11e6-9edc-b4586f1c08c8.png)


But it's not shown for the "ordinary" speakers:

![image](https://cloud.githubusercontent.com/assets/155492/14540127/c91f8f24-0283-11e6-8156-4638cefcb987.png)


There should be some way that the user can get [all the information](https://raw.githubusercontent.com/Praqma/code-conf.com/gh-pages/_events/code-cph-2016.md):

```
speakers:
  lakruzzmeekrosoft:
    title: CoDe - The Metaphors We Live By
    abstract: >
      Having our hands buried deep into DevOps and CoDe every single day, we tend to expand our vocabulary and lingo with metaphors, proverbs and anecdotes that enables us to understand and explain our domain. Mike and Lars will cover tales in the range from Tarantino's Pulp Fiction to Indonesia's stone age population.
  andrewjturner:
    title: Automation & Continuous Delivery – Lessons from the Front Line
    abstract: >
       Continuous Delivery is on the C-Level agenda and so it should be – it’s a game changer for IT change. But how do you prioritize what to do and align your stakeholders to get the most from the opportunity? Automation provides the foundation for continuous delivery, and learning from real life customer experiences across regulated industries is an excellent way to accelerate your adoption.
  ethomson:
    title: To Be Announced
    abstract: >
      To Be Announced
```
